-------------------------------------------------------------------
-- PRACTICAL WORK 2 – FLIGHT OPERATIONS & ANALYTICS
-- MASTER SCRIPT – ORACLE XE / SQL DEVELOPER
-------------------------------------------------------------------
SET DEFINE OFF;

-------------------------------------------------------------------
-- TASK 2 – IMPLEMENT WAREHOUSE AND POPULATE DATA (ETL)
-------------------------------------------------------------------
-- 2.0 CLEANUP
-------------------------------------------------------------------

-- Fact & aggregate
BEGIN EXECUTE IMMEDIATE 'DROP TABLE fact_flight_metrics PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE agg_monthly_route_perf PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Dimensions
BEGIN EXECUTE IMMEDIATE 'DROP TABLE dim_time_of_day PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE dim_aircraft PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE dim_route PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE dim_date PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Staging (simulated OLTP)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE stg_tickets PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE stg_passengers PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE stg_flights PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE stg_routes PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE stg_fleet_aircraft PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE stg_aircraft_models PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE stg_airports PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Functions & procedures
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION fn_estimated_fuel_cost';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION fn_delay_category';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE pr_load_flight_dw';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE pr_populate_agg_monthly_route';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-------------------------------------------------------------------
-- 2.1 CREATE DIMENSION TABLES
-------------------------------------------------------------------

CREATE TABLE dim_date (
    date_key          NUMBER(8)   CONSTRAINT pk_dim_date PRIMARY KEY, -- YYYYMMDD
    full_date         DATE        NOT NULL,
    day_of_week       VARCHAR2(10) NOT NULL,
    day_of_month      NUMBER(2)   NOT NULL,
    iso_week_of_year  NUMBER(2)   NOT NULL,
    month_num         NUMBER(2)   NOT NULL,
    month_name        VARCHAR2(10) NOT NULL,
    quarter_num       NUMBER(1)   NOT NULL,
    year_num          NUMBER(4)   NOT NULL,
    is_weekend        CHAR(1)     CHECK (is_weekend IN ('Y','N'))
);

CREATE TABLE dim_route (
    route_key              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    route_id               NUMBER        NOT NULL,
    route_name             VARCHAR2(20)  NOT NULL,
    origin_airport_code    VARCHAR2(3)   NOT NULL,
    origin_airport_name    VARCHAR2(100),
    origin_city            VARCHAR2(50),
    origin_country         VARCHAR2(50),
    dest_airport_code      VARCHAR2(3)   NOT NULL,
    dest_airport_name      VARCHAR2(100),
    dest_city              VARCHAR2(50),
    dest_country           VARCHAR2(50),
    distance_miles         NUMBER(6),
    route_type             VARCHAR2(20), -- Domestic / International
    CONSTRAINT pk_dim_route PRIMARY KEY (route_key),
    CONSTRAINT uk_dim_route_id UNIQUE (route_id)
);

CREATE TABLE dim_aircraft (
    aircraft_key         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tail_number          VARCHAR2(10) NOT NULL,
    model_id             NUMBER       NOT NULL,
    model_name           VARCHAR2(50) NOT NULL,
    seat_capacity        NUMBER(4)    NOT NULL,
    acquisition_date     DATE,
    effective_start_date DATE         NOT NULL,
    effective_end_date   DATE,
    is_current           CHAR(1)      DEFAULT 'Y'
                                   CHECK (is_current IN ('Y','N')),
    CONSTRAINT pk_dim_aircraft PRIMARY KEY (aircraft_key),
    CONSTRAINT uk_dim_aircraft UNIQUE (tail_number, effective_start_date)
);

CREATE TABLE dim_time_of_day (
    time_key    NUMBER(2)   CONSTRAINT pk_dim_time PRIMARY KEY,
    hour_of_day NUMBER(2)   NOT NULL CHECK (hour_of_day BETWEEN 0 AND 23),
    time_period VARCHAR2(20) NOT NULL
);

-------------------------------------------------------------------
-- 2.2 CREATE FACT TABLE
-------------------------------------------------------------------

CREATE TABLE fact_flight_metrics (
    flight_sk             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    flight_id             NUMBER       NOT NULL,

    date_key              NUMBER(8)    NOT NULL,
    route_key             NUMBER       NOT NULL,
    aircraft_key          NUMBER       NOT NULL,
    dep_time_key          NUMBER(2)    NOT NULL,

    tickets_sold          NUMBER(5)    NOT NULL,
    seat_capacity         NUMBER(4)    NOT NULL,
    load_factor_pct       NUMBER(5,2),
    total_ticket_revenue  NUMBER(12,2),
    estimated_fuel_cost   NUMBER(12,2),
    total_profit          NUMBER(12,2),
    departure_delay_min   NUMBER(6,1),
    arrival_delay_min     NUMBER(6,1),
    on_time_indicator     NUMBER(1)    CHECK (on_time_indicator IN (0,1)),
    distance_miles        NUMBER(6),

    CONSTRAINT pk_fact_flight PRIMARY KEY (flight_sk),
    CONSTRAINT fk_fact_date     FOREIGN KEY (date_key)     REFERENCES dim_date (date_key),
    CONSTRAINT fk_fact_route    FOREIGN KEY (route_key)    REFERENCES dim_route (route_key),
    CONSTRAINT fk_fact_aircraft FOREIGN KEY (aircraft_key) REFERENCES dim_aircraft (aircraft_key),
    CONSTRAINT fk_fact_time     FOREIGN KEY (dep_time_key) REFERENCES dim_time_of_day (time_key)
);

CREATE INDEX ix_fact_date     ON fact_flight_metrics (date_key);
CREATE INDEX ix_fact_route    ON fact_flight_metrics (route_key);
CREATE INDEX ix_fact_aircraft ON fact_flight_metrics (aircraft_key);
CREATE INDEX ix_fact_time     ON fact_flight_metrics (dep_time_key);

-------------------------------------------------------------------
-- 2.3 CREATE STAGING TABLES (SIMULATED OLTP)
-------------------------------------------------------------------

CREATE TABLE stg_airports (
    airport_code  VARCHAR2(3),
    airport_name  VARCHAR2(100),
    city          VARCHAR2(50),
    country       VARCHAR2(50)
);

CREATE TABLE stg_aircraft_models (
    model_id      NUMBER,
    model_name    VARCHAR2(50),
    seat_capacity NUMBER
);

CREATE TABLE stg_fleet_aircraft (
    tail_number     VARCHAR2(10),
    model_id        NUMBER,
    acquisition_date DATE
);

CREATE TABLE stg_routes (
    route_id           NUMBER,
    origin_airport     VARCHAR2(3),
    destination_airport VARCHAR2(3),
    distance_miles     NUMBER
);

CREATE TABLE stg_flights (
    flight_id           NUMBER,
    route_id            NUMBER,
    tail_number         VARCHAR2(10),
    scheduled_departure DATE,
    scheduled_arrival   DATE,
    actual_departure    DATE,
    actual_arrival      DATE
);

CREATE TABLE stg_passengers (
    passenger_id   NUMBER,
    passenger_name VARCHAR2(150),
    email          VARCHAR2(100)
);

CREATE TABLE stg_tickets (
    ticket_number  VARCHAR2(20),
    flight_id      NUMBER,
    passenger_id   NUMBER,
    price          NUMBER(10,2),
    seat_number    VARCHAR2(10)
);

-------------------------------------------------------------------
-- 2.4 POPULATE STAGING TABLES WITH SAMPLE DATA
-------------------------------------------------------------------

-- Airports
INSERT INTO stg_airports VALUES ('RIX', 'Riga International',    'Riga',     'Latvia');
INSERT INTO stg_airports VALUES ('VNO', 'Vilnius International', 'Vilnius',  'Lithuania');
INSERT INTO stg_airports VALUES ('TLL', 'Tallinn Airport',       'Tallinn',  'Estonia');
INSERT INTO stg_airports VALUES ('FRA', 'Frankfurt Main',        'Frankfurt','Germany');
INSERT INTO stg_airports VALUES ('LHR', 'Heathrow',              'London',   'United Kingdom');
INSERT INTO stg_airports VALUES ('DXB', 'Dubai International',   'Dubai',    'UAE');

-- Aircraft models
INSERT INTO stg_aircraft_models VALUES (100, 'Airbus A220-300', 145);
INSERT INTO stg_aircraft_models VALUES (101, 'Airbus A320neo',  180);
INSERT INTO stg_aircraft_models VALUES (102, 'Boeing 737-800',  189);
INSERT INTO stg_aircraft_models VALUES (103, 'Boeing 787-9',    290);
INSERT INTO stg_aircraft_models VALUES (104, 'ATR 72-600',       70);

-- Fleet aircraft
INSERT INTO stg_fleet_aircraft VALUES ('YL-ABC', 100, DATE '2022-01-10');
INSERT INTO stg_fleet_aircraft VALUES ('YL-DEF', 101, DATE '2021-05-15');
INSERT INTO stg_fleet_aircraft VALUES ('YL-GHI', 102, DATE '2020-03-20');
INSERT INTO stg_fleet_aircraft VALUES ('YL-JKL', 104, DATE '2019-09-05');
INSERT INTO stg_fleet_aircraft VALUES ('YL-MNO', 101, DATE '2023-02-18');
INSERT INTO stg_fleet_aircraft VALUES ('YL-PQR', 103, DATE '2022-11-30');

-- Routes
INSERT INTO stg_routes VALUES (1, 'RIX', 'VNO', 160);
INSERT INTO stg_routes VALUES (2, 'RIX', 'TLL', 190);
INSERT INTO stg_routes VALUES (3, 'RIX', 'FRA', 840);
INSERT INTO stg_routes VALUES (4, 'RIX', 'LHR', 1020);
INSERT INTO stg_routes VALUES (5, 'VNO', 'FRA', 900);
INSERT INTO stg_routes VALUES (6, 'TLL', 'DXB', 2500);

-- Passengers
INSERT INTO stg_passengers VALUES (1, 'Alice Johnson',  'alice@example.com');
INSERT INTO stg_passengers VALUES (2, 'Bob Smith',      'bob@example.com');
INSERT INTO stg_passengers VALUES (3, 'Carlos Garcia',  'carlos@example.com');
INSERT INTO stg_passengers VALUES (4, 'Diana Novak',    'diana@example.com');
INSERT INTO stg_passengers VALUES (5, 'Eva Schneider',  'eva@example.com');
INSERT INTO stg_passengers VALUES (6, 'Farid Hussein',  'farid@example.com');

-- Flights (~60)
DECLARE
    v_base_date DATE := DATE '2025-01-01';
    v_sched_dep DATE;
    v_sched_arr DATE;
    v_route_id  NUMBER;
    v_tail      VARCHAR2(10);
    v_block_hrs NUMBER;
BEGIN
    FOR i IN 1..60 LOOP
        v_route_id := CASE MOD(i,6)
                          WHEN 1 THEN 1
                          WHEN 2 THEN 2
                          WHEN 3 THEN 3
                          WHEN 4 THEN 4
                          WHEN 5 THEN 5
                          ELSE 6
                      END;

        v_tail := CASE MOD(i,6)
                      WHEN 1 THEN 'YL-ABC'
                      WHEN 2 THEN 'YL-DEF'
                      WHEN 3 THEN 'YL-GHI'
                      WHEN 4 THEN 'YL-JKL'
                      WHEN 5 THEN 'YL-MNO'
                      ELSE        'YL-PQR'
                  END;

        -- Schedule at 06, 12, 18, 22 each day
        v_sched_dep := v_base_date + TRUNC((i-1)/4)
                       + (CASE MOD(i,4)
                              WHEN 0 THEN 6
                              WHEN 1 THEN 12
                              WHEN 2 THEN 18
                              ELSE 22
                          END)/24;

        v_block_hrs := CASE v_route_id
                           WHEN 1 THEN 0.8
                           WHEN 2 THEN 0.8
                           WHEN 3 THEN 2.0
                           WHEN 4 THEN 2.3
                           WHEN 5 THEN 2.0
                           ELSE 5.5
                       END;

        v_sched_arr := v_sched_dep + v_block_hrs/24;

        INSERT INTO stg_flights (
            flight_id, route_id, tail_number,
            scheduled_departure, scheduled_arrival,
            actual_departure, actual_arrival
        )
        VALUES (
            i,
            v_route_id,
            v_tail,
            v_sched_dep,
            v_sched_arr,
            v_sched_dep + (DBMS_RANDOM.VALUE(-0.15, 0.35))/24,
            v_sched_arr + (DBMS_RANDOM.VALUE(-0.20, 0.60))/24
        );
    END LOOP;
    COMMIT;
END;
/
SHOW ERRORS;

-- Tickets: 40–190 per flight
DECLARE
    v_price_base NUMBER;
BEGIN
    FOR f IN (SELECT flight_id, route_id FROM stg_flights) LOOP
        v_price_base := 80 + 10 * f.route_id;

        FOR p IN 1..TRUNC(DBMS_RANDOM.VALUE(40, 190)) LOOP
            INSERT INTO stg_tickets (
                ticket_number, flight_id, passenger_id, price, seat_number
            )
            VALUES (
                'T' || f.flight_id || '-' || p,
                f.flight_id,
                MOD(p,6) + 1,
                v_price_base + DBMS_RANDOM.VALUE(-15, 25),
                'S' || LPAD(p,3,'0')
            );
        END LOOP;
    END LOOP;
    COMMIT;
END;
/
SHOW ERRORS;

-------------------------------------------------------------------
-- 2.5 PL/SQL FUNCTIONS
-------------------------------------------------------------------

CREATE OR REPLACE FUNCTION fn_estimated_fuel_cost (
    p_distance_miles IN NUMBER,
    p_seat_capacity  IN NUMBER,
    p_model_name     IN VARCHAR2
) RETURN NUMBER IS
    v_base_rate_per_mile NUMBER;
    v_capacity_factor     NUMBER;
BEGIN
    IF p_distance_miles IS NULL OR p_distance_miles <= 0 THEN
        RETURN 0;
    END IF;

    IF p_model_name LIKE 'ATR%' THEN
        v_base_rate_per_mile := 3.0;
    ELSIF p_model_name LIKE 'Airbus A220%' THEN
        v_base_rate_per_mile := 4.0;
    ELSIF p_model_name LIKE 'Airbus A320%' THEN
        v_base_rate_per_mile := 4.5;
    ELSIF p_model_name LIKE 'Boeing 737%' THEN
        v_base_rate_per_mile := 4.7;
    ELSE
        v_base_rate_per_mile := 5.0;
    END IF;

    v_capacity_factor := 1 + NVL(p_seat_capacity,150) / 600;

    RETURN ROUND(p_distance_miles * v_base_rate_per_mile * v_capacity_factor, 2);
END;
/
SHOW ERRORS;

CREATE OR REPLACE FUNCTION fn_delay_category (
    p_arrival_delay_min IN NUMBER
) RETURN VARCHAR2 IS
BEGIN
    IF p_arrival_delay_min IS NULL THEN
        RETURN 'UNKNOWN';
    ELSIF p_arrival_delay_min <= -10 THEN
        RETURN 'EARLY';
    ELSIF p_arrival_delay_min <= 15 THEN
        RETURN 'ON_TIME';
    ELSIF p_arrival_delay_min <= 60 THEN
        RETURN 'LATE';
    ELSE
        RETURN 'VERY_LATE';
    END IF;
END;
/
SHOW ERRORS;

-------------------------------------------------------------------
-- 2.6 ETL PROCEDURE: POPULATE DIMENSIONS AND FACT TABLE
-- (NLS FIX: no NLS_DATE_LANGUAGE / NLS_TERRITORY here)
-------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE pr_load_flight_dw AS
BEGIN
    ------------------------------------------------------------
    -- DIM_DATE: full year 2025
    ------------------------------------------------------------
    EXECUTE IMMEDIATE 'TRUNCATE TABLE dim_date';

    INSERT INTO dim_date (
        date_key, full_date, day_of_week, day_of_month,
        iso_week_of_year, month_num, month_name,
        quarter_num, year_num, is_weekend
    )
    SELECT
        TO_NUMBER(TO_CHAR(d, 'YYYYMMDD')) AS date_key,
        d                                  AS full_date,
        RTRIM(TO_CHAR(d, 'DAY'))          AS day_of_week,
        TO_NUMBER(TO_CHAR(d, 'DD'))       AS day_of_month,
        TO_NUMBER(TO_CHAR(d, 'IW'))       AS iso_week_of_year,
        TO_NUMBER(TO_CHAR(d, 'MM'))       AS month_num,
        TO_CHAR(d, 'MON')                 AS month_name,
        TO_NUMBER(TO_CHAR(d, 'Q'))        AS quarter_num,
        TO_NUMBER(TO_CHAR(d, 'YYYY'))     AS year_num,
        CASE
            WHEN TO_CHAR(d, 'D') IN ('1','7') THEN 'Y'
            ELSE 'N'
        END AS is_weekend
    FROM (
        SELECT DATE '2025-01-01' + LEVEL - 1 AS d
        FROM dual
        CONNECT BY LEVEL <= 365
    );

    ------------------------------------------------------------
    -- DIM_ROUTE
    ------------------------------------------------------------
    EXECUTE IMMEDIATE 'TRUNCATE TABLE dim_route';

    INSERT INTO dim_route (
        route_id, route_name,
        origin_airport_code, origin_airport_name, origin_city, origin_country,
        dest_airport_code, dest_airport_name, dest_city, dest_country,
        distance_miles, route_type
    )
    SELECT
        r.route_id,
        r.origin_airport || '-' || r.destination_airport AS route_name,
        ao.airport_code,
        ao.airport_name,
        ao.city,
        ao.country,
        ad.airport_code,
        ad.airport_name,
        ad.city,
        ad.country,
        r.distance_miles,
        CASE
            WHEN ao.country = ad.country THEN 'Domestic'
            ELSE 'International'
        END AS route_type
    FROM stg_routes r
         JOIN stg_airports ao ON r.origin_airport      = ao.airport_code
         JOIN stg_airports ad ON r.destination_airport = ad.airport_code;

    ------------------------------------------------------------
    -- DIM_AIRCRAFT
    ------------------------------------------------------------
    EXECUTE IMMEDIATE 'TRUNCATE TABLE dim_aircraft';

    INSERT INTO dim_aircraft (
        tail_number, model_id, model_name,
        seat_capacity, acquisition_date,
        effective_start_date, effective_end_date, is_current
    )
    SELECT
        fa.tail_number,
        am.model_id,
        am.model_name,
        am.seat_capacity,
        fa.acquisition_date,
        fa.acquisition_date,
        NULL,
        'Y'
    FROM stg_fleet_aircraft fa
         JOIN stg_aircraft_models am ON fa.model_id = am.model_id;

    ------------------------------------------------------------
    -- DIM_TIME_OF_DAY
    ------------------------------------------------------------
    EXECUTE IMMEDIATE 'TRUNCATE TABLE dim_time_of_day';

    INSERT INTO dim_time_of_day (time_key, hour_of_day, time_period)
    SELECT
        h AS time_key,
        h AS hour_of_day,
        CASE
            WHEN h BETWEEN 5 AND 10  THEN 'Morning'
            WHEN h BETWEEN 11 AND 16 THEN 'Afternoon'
            WHEN h BETWEEN 17 AND 21 THEN 'Evening'
            ELSE 'Night'
        END AS time_period
    FROM (
        SELECT LEVEL-1 AS h
        FROM dual
        CONNECT BY LEVEL <= 24
    );

    ------------------------------------------------------------
    -- FACT_FLIGHT_METRICS
    ------------------------------------------------------------
    EXECUTE IMMEDIATE 'TRUNCATE TABLE fact_flight_metrics';

    INSERT INTO fact_flight_metrics (
        flight_id,
        date_key, route_key, aircraft_key, dep_time_key,
        tickets_sold, seat_capacity, load_factor_pct,
        total_ticket_revenue, estimated_fuel_cost, total_profit,
        departure_delay_min, arrival_delay_min, on_time_indicator,
        distance_miles
    )
    WITH tkt AS (
        SELECT
            flight_id,
            COUNT(*)   AS tickets_sold,
            SUM(price) AS total_revenue
        FROM stg_tickets
        GROUP BY flight_id
    )
    SELECT
        f.flight_id,
        dd.date_key,
        dr.route_key,
        da.aircraft_key,
        td.time_key,
        NVL(t.tickets_sold,0) AS tickets_sold,
        da.seat_capacity,
        ROUND(NVL(t.tickets_sold,0) / da.seat_capacity * 100, 2) AS load_factor_pct,
        NVL(t.total_revenue,0) AS total_ticket_revenue,
        fn_estimated_fuel_cost(dr.distance_miles, da.seat_capacity, da.model_name)
            AS estimated_fuel_cost,
        NVL(t.total_revenue,0)
          - fn_estimated_fuel_cost(dr.distance_miles, da.seat_capacity, da.model_name)
            AS total_profit,
        ROUND( (f.actual_departure - f.scheduled_departure) * 24 * 60, 1 )
            AS departure_delay_min,
        ROUND( (f.actual_arrival   - f.scheduled_arrival)   * 24 * 60, 1 )
            AS arrival_delay_min,
        CASE
            WHEN (f.actual_arrival - f.scheduled_arrival) * 24 * 60 <= 15
            THEN 1 ELSE 0
        END AS on_time_indicator,
        dr.distance_miles
    FROM stg_flights f
         JOIN dim_route    dr ON dr.route_id    = f.route_id
         JOIN dim_aircraft da ON da.tail_number = f.tail_number
                               AND da.is_current = 'Y'
         LEFT JOIN tkt     t  ON t.flight_id    = f.flight_id
         JOIN dim_date     dd ON dd.full_date   = TRUNC(f.scheduled_departure)
         JOIN dim_time_of_day td
             ON td.hour_of_day = TO_NUMBER(TO_CHAR(f.scheduled_departure,'HH24'));

    COMMIT;
END;
/
SHOW ERRORS;

-------------------------------------------------------------------
-- 2.7 RUN ETL ONCE
-------------------------------------------------------------------

BEGIN
    pr_load_flight_dw;
END;
/

-------------------------------------------------------------------
-- 2.8 ROW-COUNT SANITY CHECK (DIM + FACT ONLY)
-------------------------------------------------------------------

SELECT *
FROM (
    SELECT 'DIM_DATE'            AS table_name, COUNT(*) AS row_count FROM dim_date
    UNION ALL
    SELECT 'DIM_ROUTE'           AS table_name, COUNT(*) AS row_count FROM dim_route
    UNION ALL
    SELECT 'DIM_AIRCRAFT'        AS table_name, COUNT(*) AS row_count FROM dim_aircraft
    UNION ALL
    SELECT 'DIM_TIME_OF_DAY'     AS table_name, COUNT(*) AS row_count FROM dim_time_of_day
    UNION ALL
    SELECT 'FACT_FLIGHT_METRICS' AS table_name, COUNT(*) AS row_count FROM fact_flight_metrics
)
ORDER BY table_name;

-------------------------------------------------------------------
-- TASK 3 – ADVANCED ANALYTICAL QUERIES
-------------------------------------------------------------------

-------------------------------------------------------------------
-- 3.1 MULTI-LEVEL AGGREGATIONS (ROLLUP / CUBE / GROUPING SETS)
-------------------------------------------------------------------

-- 3.1.1 ROLLUP: revenue, profit, load factor by year, quarter, route
SELECT
    dd.year_num,
    dd.quarter_num,
    dr.route_name,
    SUM(ff.total_ticket_revenue) AS total_revenue,
    SUM(ff.total_profit)         AS total_profit,
    ROUND(AVG(ff.load_factor_pct),2) AS avg_load_factor,
    GROUPING(dd.year_num)       AS grp_year,
    GROUPING(dd.quarter_num)    AS grp_quarter,
    GROUPING(dr.route_name)     AS grp_route
FROM fact_flight_metrics ff
     JOIN dim_date  dd ON ff.date_key  = dd.date_key
     JOIN dim_route dr ON ff.route_key = dr.route_key
GROUP BY ROLLUP (dd.year_num, dd.quarter_num, dr.route_name)
ORDER BY dd.year_num, dd.quarter_num, dr.route_name;

-- 3.1.2 CUBE: avg arrival delay & on-time rate by origin country and aircraft model
SELECT
    dr.origin_country,
    da.model_name,
    ROUND(AVG(ff.arrival_delay_min),1)          AS avg_arrival_delay_min,
    ROUND(AVG(ff.on_time_indicator)*100,2)      AS on_time_pct
FROM fact_flight_metrics ff
     JOIN dim_route    dr ON ff.route_key    = dr.route_key
     JOIN dim_aircraft da ON ff.aircraft_key = da.aircraft_key
GROUP BY CUBE (dr.origin_country, da.model_name)
ORDER BY dr.origin_country, da.model_name;

-- 3.1.3 GROUPING SETS: monthly revenue and load factor by route & route type
SELECT
    dd.year_num,
    dd.month_num,
    dr.route_type,
    dr.route_name,
    SUM(ff.total_ticket_revenue)      AS total_revenue,
    ROUND(AVG(ff.load_factor_pct),2)  AS avg_load_factor
FROM fact_flight_metrics ff
     JOIN dim_date  dd ON ff.date_key  = dd.date_key
     JOIN dim_route dr ON ff.route_key = dr.route_key
GROUP BY GROUPING SETS (
    (dd.year_num, dd.month_num, dr.route_type, dr.route_name),
    (dd.year_num, dd.month_num, dr.route_type),
    (dd.year_num, dd.month_num),
    ()
)
ORDER BY dd.year_num, dd.month_num, dr.route_type, dr.route_name;

-- 3.1.4 ROLLUP with PL/SQL function: flights by delay category and year
SELECT
    dd.year_num,
    fn_delay_category(ff.arrival_delay_min) AS delay_category,
    COUNT(*)                                AS flight_count,
    ROUND(AVG(ff.arrival_delay_min),1)      AS avg_arrival_delay,
    GROUPING(dd.year_num)                   AS grp_year,
    GROUPING(fn_delay_category(ff.arrival_delay_min)) AS grp_cat
FROM fact_flight_metrics ff
     JOIN dim_date dd ON ff.date_key = dd.date_key
GROUP BY ROLLUP (dd.year_num, fn_delay_category(ff.arrival_delay_min))
ORDER BY dd.year_num, delay_category;

-------------------------------------------------------------------
-- 3.2 QUERIES USING PL/SQL FUNCTIONS
-------------------------------------------------------------------

-- 3.2.1 Fuel-cost intensity by aircraft model and route type
SELECT
    da.model_name,
    dr.route_type,
    ROUND(
        AVG(
            fn_estimated_fuel_cost(ff.distance_miles,
                                   ff.seat_capacity,
                                   da.model_name)
            / NULLIF(ff.distance_miles,0)
        ),
        2
    ) AS avg_fuel_cost_per_mile
FROM fact_flight_metrics ff
     JOIN dim_route    dr ON ff.route_key    = dr.route_key
     JOIN dim_aircraft da ON ff.aircraft_key = da.aircraft_key
GROUP BY da.model_name, dr.route_type
ORDER BY da.model_name, dr.route_type;

-- 3.3 MODEL CLAUSE – WHAT-IF ANALYSIS (FIXED)
-- What if fuel prices increase by 15%? Impact on yearly route profitability
SELECT
    year_num,
    route_name,
    scenario,
    ROUND(total_revenue,2)    AS total_revenue,
    ROUND(total_fuel_cost,2)  AS total_fuel_cost,
    ROUND(total_profit,2)     AS total_profit
FROM (
    SELECT
        dd.year_num,
        dr.route_name,
        CAST('BASE' AS VARCHAR2(20)) AS scenario,   -- <<< KEY FIX
        SUM(ff.total_ticket_revenue) AS total_revenue,
        SUM(ff.estimated_fuel_cost)  AS total_fuel_cost,
        SUM(ff.total_profit)         AS total_profit
    FROM fact_flight_metrics ff
         JOIN dim_date  dd ON ff.date_key  = dd.date_key
         JOIN dim_route dr ON ff.route_key = dr.route_key
    GROUP BY dd.year_num, dr.route_name
)
MODEL
    PARTITION BY (year_num, route_name)
    DIMENSION BY (scenario)
    MEASURES (total_revenue, total_fuel_cost, total_profit)
    RULES UPSERT (
        total_revenue['FUEL+15']   = total_revenue['BASE'],
        total_fuel_cost['FUEL+15'] = total_fuel_cost['BASE'] * 1.15,
        total_profit['FUEL+15']    = total_revenue['FUEL+15']
                                     - total_fuel_cost['FUEL+15']
    )
ORDER BY year_num, route_name, scenario;

-------------------------------------------------------------------
-- TASK 4 – AGGREGATE TABLE
-------------------------------------------------------------------

-- 4.1 Aggregate table for monthly route performance
CREATE TABLE agg_monthly_route_perf (
    year_num              NUMBER(4)    NOT NULL,
    month_num             NUMBER(2)    NOT NULL,
    route_key             NUMBER       NOT NULL,
    route_name            VARCHAR2(20) NOT NULL,

    total_flights         NUMBER,
    total_tickets_sold    NUMBER,
    total_revenue         NUMBER(14,2),
    total_est_fuel_cost   NUMBER(14,2),
    total_profit          NUMBER(14,2),
    avg_load_factor_pct   NUMBER(5,2),
    avg_arrival_delay_min NUMBER(6,2),
    on_time_pct           NUMBER(5,2),

    CONSTRAINT pk_agg_monthly_route PRIMARY KEY (year_num, month_num, route_key)
);

-- 4.2 Population procedure (TRUNCATE + INSERT ... SELECT ... GROUP BY)
CREATE OR REPLACE PROCEDURE pr_populate_agg_monthly_route AS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE agg_monthly_route_perf';

    INSERT INTO agg_monthly_route_perf (
        year_num, month_num, route_key, route_name,
        total_flights, total_tickets_sold,
        total_revenue, total_est_fuel_cost, total_profit,
        avg_load_factor_pct, avg_arrival_delay_min, on_time_pct
    )
    SELECT
        dd.year_num,
        dd.month_num,
        dr.route_key,
        dr.route_name,
        COUNT(*)                      AS total_flights,
        SUM(ff.tickets_sold)          AS total_tickets_sold,
        SUM(ff.total_ticket_revenue)  AS total_revenue,
        SUM(ff.estimated_fuel_cost)   AS total_est_fuel_cost,
        SUM(ff.total_profit)          AS total_profit,
        ROUND(AVG(ff.load_factor_pct), 2)    AS avg_load_factor_pct,
        ROUND(AVG(ff.arrival_delay_min), 2)  AS avg_arrival_delay_min,
        ROUND(AVG(ff.on_time_indicator)*100,2) AS on_time_pct
    FROM fact_flight_metrics ff
         JOIN dim_date  dd ON ff.date_key  = dd.date_key
         JOIN dim_route dr ON ff.route_key = dr.route_key
    GROUP BY dd.year_num, dd.month_num, dr.route_key, dr.route_name;

    COMMIT;
END;
/
SHOW ERRORS;

-- 4.3 Run population procedure
BEGIN
    pr_populate_agg_monthly_route;
END;
/

-- 4.4 Sample analytical query on aggregate table (fast query)
SELECT
    year_num,
    month_num,
    route_name,
    total_flights,
    total_revenue,
    total_profit,
    avg_load_factor_pct,
    on_time_pct
FROM agg_monthly_route_perf
WHERE year_num = 2025
ORDER BY month_num, route_name;

-- 4.5 EXPLAIN PLAN comparison (slow vs fast)

-- SLOW: directly on fact table
EXPLAIN PLAN FOR
SELECT
    dd.year_num,
    dd.month_num,
    dr.route_name,
    COUNT(*)                     AS total_flights,
    SUM(ff.total_ticket_revenue) AS total_revenue,
    SUM(ff.total_profit)         AS total_profit,
    ROUND(AVG(ff.load_factor_pct),2) AS avg_load_factor_pct,
    ROUND(AVG(ff.on_time_indicator)*100,2) AS on_time_pct
FROM fact_flight_metrics ff
     JOIN dim_date  dd ON ff.date_key  = dd.date_key
     JOIN dim_route dr ON ff.route_key = dr.route_key
GROUP BY dd.year_num, dd.month_num, dr.route_name;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- FAST: on aggregate table
EXPLAIN PLAN FOR
SELECT
    year_num,
    month_num,
    route_name,
    total_flights,
    total_revenue,
    total_profit,
    avg_load_factor_pct,
    on_time_pct
FROM agg_monthly_route_perf;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-------------------------------------------------------------------
-- OPTIONAL: FINAL ROW-COUNTS INCLUDING AGG TABLE
-------------------------------------------------------------------

SELECT *
FROM (
    SELECT 'DIM_DATE'               AS table_name, COUNT(*) AS row_count FROM dim_date
    UNION ALL
    SELECT 'DIM_ROUTE'              AS table_name, COUNT(*) AS row_count FROM dim_route
    UNION ALL
    SELECT 'DIM_AIRCRAFT'           AS table_name, COUNT(*) AS row_count FROM dim_aircraft
    UNION ALL
    SELECT 'DIM_TIME_OF_DAY'        AS table_name, COUNT(*) AS row_count FROM dim_time_of_day
    UNION ALL
    SELECT 'FACT_FLIGHT_METRICS'    AS table_name, COUNT(*) AS row_count FROM fact_flight_metrics
    UNION ALL
    SELECT 'AGG_MONTHLY_ROUTE_PERF' AS table_name, COUNT(*) AS row_count FROM agg_monthly_route_perf
)
ORDER BY table_name;
